name = "warden-worker"
main = "src/entry.js"
compatibility_date = "2025-09-19"
keep_vars = true
workers_dev = false
preview_urls = false

[durable_objects]
bindings = [
  { name = "HEAVY_DO", class_name = "HeavyDo" },
  { name = "NOTIFY_DO", class_name = "NotifyDo" }
]

[[migrations]]
tag = "do_v1"
new_sqlite_classes = ["HeavyDo"]

[[migrations]]
tag = "do_v2"
new_sqlite_classes = ["NotifyDo"]

[build]
command = "cargo install --locked -q worker-build --version 0.8.3 && worker-build --release --locked"

[assets]
directory = "./public/web-vault"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
run_worker_first = ["/api/*", "/identity/*", "/notifications/*"]

[vars]
# SIGNUPS_ALLOWED = "true"

[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "vault1"
database_id = "2b65e74a-cd5b-4d3e-8a42-8a98d5153e9e"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "ATTACHMENTS_KV"
